version: '3'
services:
  link_extractor_python:
    image: python:3.8
    container_name: link_extractor_python
    ports:
      - "5000:5000"
    volumes:
      - ./python_app:/app
    command: python /app/link_extractor.py
    depends_on:
      - redis

  link_extractor_ruby:
    image: ruby:2.7
    container_name: link_extractor_ruby
    ports:
      - "5001:5001"
    volumes:
      - ./ruby_app:/app
    command: ruby /app/link_extractor.rb
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
